config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions:      'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'static_pages#home'

  get '/home',          to: 'static_pages#home', as: 'home'
  get '/menu/:weekday', to: 'orders#new',        as: 'menu'

  resources :orders, only: [:new, :create]

  namespace :admin do
    root to: 'users#index'

    get '/orders/calendar', to: 'orders#calendar', as: 'calendar'

    resources :users,   only: [:index]
    resources :courses, except: [:destroy]
    resources :orders,  only: [:index]
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
          registrations: 'api/v1/registrations',
          sessions: 'api/v1/sessions'
      }

      resources :orders,  only: [:index]
    end
  end
end

app/views/layouts/_flash.haml
.flash-messages
  - flash.each do |key, value|
    %div{class: "alert alert-dismissible alert-#{flash_alert_converter key}", role: 'alert'}
      %button.close{ 'data-dismiss': 'alert' } &times
      - case key
      - when 'success'
        %i.glyphicon.glyphicon-ok-sign
      - when 'danger'
        %i.glyphicon.glyphicon-remove-sign
      - when 'warning'
        %i.glyphicon.glyphicon-exclamation-sign
      - else
        %i.glyphicon.glyphicon-info-sign
      = value

app/views/layouts/_footer.haml
%footer
  .container
    %p.text-center
      Copyright &copy; Lunch Ordering 2017

app/views/layouts/_header.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    = link_to 'Lunch Ordering', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Home', home_path
        - if user_signed_in?
          - if current_user.is_admin?
            %li
              = link_to 'Admin panel', admin_root_path, class: 'nav-link'
          %li.dropdown
            %a.dropdown-toggle{ href: '#', 'data-toggle': 'dropdown',
                                  role: 'button', 'aria-expanded': 'false' }
              = current_user.name
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li
                = link_to 'Settings', edit_user_registration_path
              %li.divider
              %li
                = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Log in', new_user_session_path
          %li
            = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.haml
!!!
%html
  %head
    %title
      = full_title(yield :title)
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'

    = render 'layouts/flash'

    .container
      = yield

    = render 'layouts/footer'

    = debug(params) if Rails.env.development?